

fabien_events_engine_events:
    resource: "@FabienEventsEngineBundle/Resources/config/routing/event.yml"
    prefix:   /event

fabien_events_engine_dates:
    resource: "@FabienEventsEngineBundle/Resources/config/routing/date.yml"
    prefix:   /date

fabien_events_engine_image:
    resource: "@FabienEventsEngineBundle/Resources/config/routing/image.yml"
    prefix:   /image

fabien_events_engine_ajax:
    resource: "@FabienEventsEngineBundle/Resources/config/routing/ajax.yml"
    prefix:   /ajax



fabien_events_engine_home:
    path: /
    defaults:
      _controller: FabienEventsEngineBundle:Home:displayHome





fabien_events_blog_list:
  path: /blog-tango
  defaults:
    _controller: FabienEventsEngineBundle:Post:listPublic

fabien_events_blog_rss:
  path: /blog-tango/rss
  defaults:
    _controller: FabienEventsEngineBundle:Post:rss

fabien_events_blog_view:
  path: /blog-tango/{slug}
  defaults:
    _controller: FabienEventsEngineBundle:Post:viewPublic

fabien_events_engine_cours:
  path: /tango-class/{slug}
  defaults:
    _controller: FabienEventsEngineBundle:City:listCours

fabien_events_coutry_list:
    path: /country
    defaults:
      _controller: FabienEventsEngineBundle:Country:list

fabien_events_coutry_listcities:
    path: /country/{slug}
    defaults:
      _controller: FabienEventsEngineBundle:Country:listCities


fabien_events_city_post_id:
    path: /city/id
    defaults :
        _controller: FabienEventsEngineBundle:City:viewId


fabien_events_city_slug:
  path: /city/{slug}
  defaults :
    _controller : FabienEventsEngineBundle:City:viewSlug

fabien_events_city_slug_rss:
  path: /city/{slug}/rss
  defaults :
    _controller : FabienEventsEngineBundle:City:viewSlugRss


fabien_events_city_slug_period:
  path: /city/{slug}/{period}
  defaults :
    _controller : FabienEventsEngineBundle:City:viewSlug


fabien_events_engine_state:
    path:      state/{slug}
    defaults:
        _controller: FabienEventsEngineBundle:State:viewState

fabien_events_engine_city:
    path:      city/{slug}
    defaults:
        _controller: FabienEventsEngineBundle:City:viewSlug

fabien_events_engine_city_period:
    path:      city/{slug}/{period}
    defaults:
        _controller: FabienEventsEngineBundle:City:viewSlug




fabien_events_engine_bigevents:
  path: /category/
  defaults:
    _controller: FabienEventsEngineBundle:Lister:bigEventsHome


fabien_events_engine_bigevents_list:
  path: /category/{slug}
  defaults:
    _controller: FabienEventsEngineBundle:Lister:bigEventsList


fabien_events_engine_stage_list:
  path: /tango-workshop/{location}
  defaults :
    _controller: FabienEventsEngineBundle:Lister:stagesList
