fabien_user:
    resource: "@FabienUserBundle/Resources/config/routing.yml"
    prefix:   /

locale:
  path: /
  defaults:  { _controller: FabienEventsEngineBundle:Home:displayHome }

fabien_events_engine:
    resource: "@FabienEventsEngineBundle/Resources/config/routing.yml"
    prefix:    /{_locale}/
    requirements:
      _locale: en|fr

fabien_events_blog_list.default:
  path: /blog-tango
  defaults:
    _controller: FabienEventsEngineBundle:Post:listPublic

fabien_events_blog_view.default:
  path: /blog-tango/{slug}
  defaults:
    _controller: FabienEventsEngineBundle:Post:viewPublic

fabien_events_coutry_list.default:
    path: /country
    defaults:
      _controller: FabienEventsEngineBundle:Country:list

date_view.default:
  path: /date/{id}
  defaults: { _controller:"FabienEventsEngineBundle:Date:view"}



fabien_events_engine_admin:
    resource: "@FabienEventsEngineBundle/Resources/config/routing/admin.yml"
    prefix:   /admin


fabien_sitemap:
  path: /sitemap-{typesitemap}.xml
  defaults:
    _controller: FabienEventsEngineBundle:Home:createSiteMap



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

logout:
    path: /logout
