# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.twig_runtime:
        class: Fabien\EventsEngineBundle\Twig\AppExtension
        tags: [twig.extension]
